import { inspectImportFile } from "./exportData";
import type { ExportedData } from "./types";

/**
 * A filled-in praesidium for reviewing the app (public/sample-data.json,
 * regenerated by `npm run sample-data`). Gated behind ?demo=1 so real members
 * never meet a button that would wipe their records.
 */
export function isDemoMode(): boolean {
  if (typeof window === "undefined") return false;
  return new URLSearchParams(window.location.search).has("demo");
}

/** Fetches and validates the fixture; null when unavailable or malformed. */
export async function fetchSampleData(): Promise<ExportedData | null> {
  try {
    const res = await fetch("/sample-data.json", { cache: "no-store" });
    if (!res.ok) return null;
    const check = inspectImportFile(await res.json());
    return check.ok ? check.data : null;
  } catch {
    return null;
  }
}
